create table IF NOT EXISTS pais (
    CodPais INTEGER not null primary key AUTO_INCREMENT, 
	Nombre char(35) not null
) engine=MyISAM; 

INSERT INTO pais (Nombre) VALUES('Afganistan');
INSERT INTO pais (Nombre) VALUES('Africa del Sur');
INSERT INTO pais (Nombre) VALUES('Albania');
INSERT INTO pais (Nombre) VALUES('Alemania');
INSERT INTO pais (Nombre) VALUES('Andorra');
INSERT INTO pais (Nombre) VALUES('Angola');
INSERT INTO pais (Nombre) VALUES('Antigua y Barbuda');
INSERT INTO pais (Nombre) VALUES('Antillas Holandesas');
INSERT INTO pais (Nombre) VALUES('Arabia Saudita');
INSERT INTO pais (Nombre) VALUES('Argelia');
INSERT INTO pais (Nombre) VALUES('Argentina');
INSERT INTO pais (Nombre) VALUES('Armenia');
INSERT INTO pais (Nombre) VALUES('Aruba');
INSERT INTO pais (Nombre) VALUES('Australia');
INSERT INTO pais (Nombre) VALUES('Austria');
INSERT INTO pais (Nombre) VALUES('Azerbaijan');
INSERT INTO pais (Nombre) VALUES('Bahamas');
INSERT INTO pais (Nombre) VALUES('Bahrain');
INSERT INTO pais (Nombre) VALUES('Bangladesh');
INSERT INTO pais (Nombre) VALUES('Barbados');
INSERT INTO pais (Nombre) VALUES('Belarusia');
INSERT INTO pais (Nombre) VALUES('Belgica');
INSERT INTO pais (Nombre) VALUES('Belice');
INSERT INTO pais (Nombre) VALUES('Benin');
INSERT INTO pais (Nombre) VALUES('Bermudas');
INSERT INTO pais (Nombre) VALUES('Bolivia');
INSERT INTO pais (Nombre) VALUES('Bosnia');
INSERT INTO pais (Nombre) VALUES('Botswana');
INSERT INTO pais (Nombre) VALUES('Brasil');
INSERT INTO pais (Nombre) VALUES('Brunei Darussulam');
INSERT INTO pais (Nombre) VALUES('Bulgaria');
INSERT INTO pais (Nombre) VALUES('Burkina Faso');
INSERT INTO pais (Nombre) VALUES('Burundi');
INSERT INTO pais (Nombre) VALUES('Butan');
INSERT INTO pais (Nombre) VALUES('Camboya');
INSERT INTO pais (Nombre) VALUES('Camerun');
INSERT INTO pais (Nombre) VALUES('Canada');
INSERT INTO pais (Nombre) VALUES('Cape Verde');
INSERT INTO pais (Nombre) VALUES('Chad');
INSERT INTO pais (Nombre) VALUES('Chile');
INSERT INTO pais (Nombre) VALUES('China');
INSERT INTO pais (Nombre) VALUES('Chipre');
INSERT INTO pais (Nombre) VALUES('Colombia');
INSERT INTO pais (Nombre) VALUES('Comoros');
INSERT INTO pais (Nombre) VALUES('Congo');
INSERT INTO pais (Nombre) VALUES('Corea del Norte');
INSERT INTO pais (Nombre) VALUES('Corea del Sur');
INSERT INTO pais (Nombre) VALUES('Costa de Marfíl');
INSERT INTO pais (Nombre) VALUES('Costa Rica');
INSERT INTO pais (Nombre) VALUES('Croasia');
INSERT INTO pais (Nombre) VALUES('Cuba');
INSERT INTO pais (Nombre) VALUES('Dinamarca');
INSERT INTO pais (Nombre) VALUES('Djibouti');
INSERT INTO pais (Nombre) VALUES('Dominica');
INSERT INTO pais (Nombre) VALUES('Ecuador');
INSERT INTO pais (Nombre) VALUES('Egipto');
INSERT INTO pais (Nombre) VALUES('El Salvador');
INSERT INTO pais (Nombre) VALUES('Emiratos Arabes Unidos');
INSERT INTO pais (Nombre) VALUES('Eritrea');
INSERT INTO pais (Nombre) VALUES('Eslovenia');
INSERT INTO pais (Nombre) VALUES('España');
INSERT INTO pais (Nombre) VALUES('Estados Unidos');
INSERT INTO pais (Nombre) VALUES('Estonia');
INSERT INTO pais (Nombre) VALUES('Etiopia');
INSERT INTO pais (Nombre) VALUES('Fiji');
INSERT INTO pais (Nombre) VALUES('Filipinas');
INSERT INTO pais (Nombre) VALUES('Finlandia');
INSERT INTO pais (Nombre) VALUES('Francia');
INSERT INTO pais (Nombre) VALUES('Gabon');
INSERT INTO pais (Nombre) VALUES('Gambia');
INSERT INTO pais (Nombre) VALUES('Georgia');
INSERT INTO pais (Nombre) VALUES('Ghana');
INSERT INTO pais (Nombre) VALUES('Granada');
INSERT INTO pais (Nombre) VALUES('Grecia');
INSERT INTO pais (Nombre) VALUES('Groenlandia');
INSERT INTO pais (Nombre) VALUES('Guadalupe');
INSERT INTO pais (Nombre) VALUES('Guam');
INSERT INTO pais (Nombre) VALUES('Guatemala');
INSERT INTO pais (Nombre) VALUES('Guayana Francesa');
INSERT INTO pais (Nombre) VALUES('Guerney');
INSERT INTO pais (Nombre) VALUES('Guinea');
INSERT INTO pais (Nombre) VALUES('Guinea-Bissau');
INSERT INTO pais (Nombre) VALUES('Guinea Equatorial');
INSERT INTO pais (Nombre) VALUES('Guyana');
INSERT INTO pais (Nombre) VALUES('Haiti');
INSERT INTO pais (Nombre) VALUES('Holanda');
INSERT INTO pais (Nombre) VALUES('Honduras');
INSERT INTO pais (Nombre) VALUES('Hong Kong');
INSERT INTO pais (Nombre) VALUES('Hungria');
INSERT INTO pais (Nombre) VALUES('India');
INSERT INTO pais (Nombre) VALUES('Indonesia');
INSERT INTO pais (Nombre) VALUES('Irak');
INSERT INTO pais (Nombre) VALUES('Iran');
INSERT INTO pais (Nombre) VALUES('Irlanda');
INSERT INTO pais (Nombre) VALUES('Islandia');
INSERT INTO pais (Nombre) VALUES('Islas Caiman');
INSERT INTO pais (Nombre) VALUES('Islas Faroe');
INSERT INTO pais (Nombre) VALUES('Islas Malvinas');
INSERT INTO pais (Nombre) VALUES('Islas Marshall');
INSERT INTO pais (Nombre) VALUES('Islas Solomon');
INSERT INTO pais (Nombre) VALUES('Islas Virgenes Britanicas');
INSERT INTO pais (Nombre) VALUES('Islas Virgenes (U.S.)');
INSERT INTO pais (Nombre) VALUES('Israel');
INSERT INTO pais (Nombre) VALUES('Italia');
INSERT INTO pais (Nombre) VALUES('Jamaica');
INSERT INTO pais (Nombre) VALUES('Japon');
INSERT INTO pais (Nombre) VALUES('Jersey');
INSERT INTO pais (Nombre) VALUES('Jordania');
INSERT INTO pais (Nombre) VALUES('Kazakhstan');
INSERT INTO pais (Nombre) VALUES('Kenia');
INSERT INTO pais (Nombre) VALUES('Kiribati');
INSERT INTO pais (Nombre) VALUES('Kuwait');
INSERT INTO pais (Nombre) VALUES('Kyrgyzstan');
INSERT INTO pais (Nombre) VALUES('Laos');
INSERT INTO pais (Nombre) VALUES('Latvia');
INSERT INTO pais (Nombre) VALUES('Lesotho');
INSERT INTO pais (Nombre) VALUES('Libano');
INSERT INTO pais (Nombre) VALUES('Liberia');
INSERT INTO pais (Nombre) VALUES('Libia');
INSERT INTO pais (Nombre) VALUES('Liechtenstein');
INSERT INTO pais (Nombre) VALUES('Lituania');
INSERT INTO pais (Nombre) VALUES('Luxemburgo');
INSERT INTO pais (Nombre) VALUES('Macao');
INSERT INTO pais (Nombre) VALUES('Macedonia');
INSERT INTO pais (Nombre) VALUES('Madagascar');
INSERT INTO pais (Nombre) VALUES('Malasia');
INSERT INTO pais (Nombre) VALUES('Malawi');
INSERT INTO pais (Nombre) VALUES('Maldivas');
INSERT INTO pais (Nombre) VALUES('Mali');
INSERT INTO pais (Nombre) VALUES('Malta');
INSERT INTO pais (Nombre) VALUES('Marruecos');
INSERT INTO pais (Nombre) VALUES('Martinica');
INSERT INTO pais (Nombre) VALUES('Mauricio');
INSERT INTO pais (Nombre) VALUES('Mauritania');
INSERT INTO pais (Nombre) VALUES('Mexico');
INSERT INTO pais (Nombre) VALUES('Micronesia');
INSERT INTO pais (Nombre) VALUES('Moldova');
INSERT INTO pais (Nombre) VALUES('Monaco');
INSERT INTO pais (Nombre) VALUES('Mongolia');
INSERT INTO pais (Nombre) VALUES('Mozambique');
INSERT INTO pais (Nombre) VALUES('Myanmar (Burma)');
INSERT INTO pais (Nombre) VALUES('Namibia');
INSERT INTO pais (Nombre) VALUES('Nepal');
INSERT INTO pais (Nombre) VALUES('Nicaragua');
INSERT INTO pais (Nombre) VALUES('Niger');
INSERT INTO pais (Nombre) VALUES('Nigeria');
INSERT INTO pais (Nombre) VALUES('Noruega');
INSERT INTO pais (Nombre) VALUES('Nueva Caledonia');
INSERT INTO pais (Nombre) VALUES('Nueva Zealandia');
INSERT INTO pais (Nombre) VALUES('Oman');
INSERT INTO pais (Nombre) VALUES('Pakistan');
INSERT INTO pais (Nombre) VALUES('Palestina');
INSERT INTO pais (Nombre) VALUES('Panama');
INSERT INTO pais (Nombre) VALUES('Papua Nueva Guinea');
INSERT INTO pais (Nombre) VALUES('Paraguay');
INSERT INTO pais (Nombre) VALUES('Peru');
INSERT INTO pais (Nombre) VALUES('Polinesia Francesa');
INSERT INTO pais (Nombre) VALUES('Polonia');
INSERT INTO pais (Nombre) VALUES('Portugal');
INSERT INTO pais (Nombre) VALUES('Puerto Rico');
INSERT INTO pais (Nombre) VALUES('Qatar');
INSERT INTO pais (Nombre) VALUES('Reino Unido');
INSERT INTO pais (Nombre) VALUES('Republica Centroafricana');
INSERT INTO pais (Nombre) VALUES('Republica Checa');
INSERT INTO pais (Nombre) VALUES('Republica Democratica del Congo');
INSERT INTO pais (Nombre) VALUES('Republica Dominicana');
INSERT INTO pais (Nombre) VALUES('Republica Eslovaca');
INSERT INTO pais (Nombre) VALUES('Reunion');
INSERT INTO pais (Nombre) VALUES('Ruanda');
INSERT INTO pais (Nombre) VALUES('Rumania');
INSERT INTO pais (Nombre) VALUES('Rusia');
INSERT INTO pais (Nombre) VALUES('Sahara');
INSERT INTO pais (Nombre) VALUES('Samoa');
INSERT INTO pais (Nombre) VALUES('San Cristobal-Nevis (St. Kitts)');
INSERT INTO pais (Nombre) VALUES('San Marino');
INSERT INTO pais (Nombre) VALUES('San Vincente y las Granadinas');
INSERT INTO pais (Nombre) VALUES('Santa Helena');
INSERT INTO pais (Nombre) VALUES('Santa Lucia');
INSERT INTO pais (Nombre) VALUES('Santa Sede (Vaticano)');
INSERT INTO pais (Nombre) VALUES('Sao Tome & Principe');
INSERT INTO pais (Nombre) VALUES('Senegal');
INSERT INTO pais (Nombre) VALUES('Seychelles');
INSERT INTO pais (Nombre) VALUES('Sierra Leona');
INSERT INTO pais (Nombre) VALUES('Singapur');
INSERT INTO pais (Nombre) VALUES('Siria');
INSERT INTO pais (Nombre) VALUES('Somalia');
INSERT INTO pais (Nombre) VALUES('Sri Lanka (Ceilan)');
INSERT INTO pais (Nombre) VALUES('Sudan');
INSERT INTO pais (Nombre) VALUES('Suecia');
INSERT INTO pais (Nombre) VALUES('Suiza');
INSERT INTO pais (Nombre) VALUES('Sur Africa');
INSERT INTO pais (Nombre) VALUES('Surinam');
INSERT INTO pais (Nombre) VALUES('Swaziland');
INSERT INTO pais (Nombre) VALUES('Tailandia');
INSERT INTO pais (Nombre) VALUES('Taiwan');
INSERT INTO pais (Nombre) VALUES('Tajikistan');
INSERT INTO pais (Nombre) VALUES('Tanzania');
INSERT INTO pais (Nombre) VALUES('Timor Oriental');
INSERT INTO pais (Nombre) VALUES('Togo');
INSERT INTO pais (Nombre) VALUES('Tokelau');
INSERT INTO pais (Nombre) VALUES('Tonga');
INSERT INTO pais (Nombre) VALUES('Trinidad & Tobago');
INSERT INTO pais (Nombre) VALUES('Tunisia');
INSERT INTO pais (Nombre) VALUES('Turkmenistan');
INSERT INTO pais (Nombre) VALUES('Turquia');
INSERT INTO pais (Nombre) VALUES('Ucrania');
INSERT INTO pais (Nombre) VALUES('Uganda');
INSERT INTO pais (Nombre) VALUES('Union Europea');
INSERT INTO pais (Nombre) VALUES('Uruguay');
INSERT INTO pais (Nombre) VALUES('Uzbekistan');
INSERT INTO pais (Nombre) VALUES('Vanuatu');
INSERT INTO pais (Nombre) VALUES('Venezuela');
INSERT INTO pais (Nombre) VALUES('Vietnam');
INSERT INTO pais (Nombre) VALUES('Yemen');
INSERT INTO pais (Nombre) VALUES('Yugoslavia');
INSERT INTO pais (Nombre) VALUES('Zambia');
INSERT INTO pais (Nombre) VALUES('Zimbabwe');